### PR TITLE
Add Unit Tests for the Projects and Todos in the Todo-List Web App

### PR DESCRIPTION
**Pull request by KabohaJeanMark**
- Setup and configure jest for unit testing
- Write unit tests for projects and todos.
- Refactor some methods to use pure functions that are better suited for unit tests for example the create project method.
- Use Behaviour driven design while testing to write both positive and negative tests to cover a variety of edge cases.
- Use describe blocks to group similar tests and enable DRY JS.
- Create a tests module and store all those files there.
- Uodate the README with instructions on how to run the tests with the following command
```
npm run test
```

### CODE REVIEW

**Review by eliasecasta — CHANGES_REQUESTED** [review]
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @KabohaJeanMark, I am Elias, your reviewer for this PR

Well done so far with your project!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [ ] For this project it is needed that you test all the functions in your app, right now, you are only creating an object and checking its content which is not enough to comply with the project requirements. Please add unit tests for all your functions.

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by KabohaJeanMark** [comment]
Thanks, 👍🏾  @e71az for the quick feedback.

I have implemented the feedback and added more unit tests for more of the pure functions. 

I have tested all the functions I am able to test.

However, a few functions are getting extremely complex and calling multiple functions within them. Testing these goes into difficult integration tests

**Comment by eliasecasta** [comment]
> Thanks, 👍🏾 @e71az for the quick feedback.
> 
> I have implemented the feedback and added more unit tests for more of the pure functions.
> 
> I have tested all the functions I am able to test.
> 
> However, a few functions are getting extremely complex and calling multiple functions within them. Testing these goes into difficult integration tests

Unit tests should be enough Jean, well done!

**Review by eliasecasta — APPROVED** [review]
## Status:  Approved 🟢

Hi, @KabohaJeanMark, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
